
unified_test:
  image: "rust:1.32-stretch"
  variables:
    LC_ALL: "C.UTF-8"
    LANG: "C.UTF-8"
    POSTGRES_DB: "fatcat_test"
    POSTGRES_USER: "fatcat_user"
    POSTGRES_PASSWORD: "fatcat_pw"
    DATABASE_URL: "postgres://fatcat_user:fatcat_pw@postgres/fatcat_test"
    TEST_DATABASE_URL: "postgres://fatcat_user:fatcat_pw@postgres/fatcat_test"
  services:
    - "postgres:11"
  before_script:
    - cargo install diesel_cli --version 1.3.1
    - apt update -qy
    - apt install -y python3-dev python3-pip python3-wheel python3-requests python3-six python3-pytest libsnappy-dev libsodium-dev
    - pip3 install pipenv
    - pipenv --version
  script:
    - rustc --version && cargo --version && diesel --version
    - cd rust
    - cp example.env .env
    - diesel database reset && diesel migration run
    - cargo build
    - cargo test -- --test-threads 1
    - cargo run --bin fatcatd &
    - cd ../python_client
    - pytest-3
    - cd ../python
    - cp example.env .env
    - pipenv install --dev --deploy
    - pipenv run pytest --cov
    - pipenv run ./tests/cli.sh
    # Just errors
    - pipenv run pylint -E fatcat*.py fatcat_tools fatcat_web tests/*.py

rust_build_release:
  only:
    - tags  # doesn't build for most commits; only tagged
  image: "rust:1.32-stretch"
  variables:
    LC_ALL: "C.UTF-8"
    LANG: "C.UTF-8"
  script:
    - rustc --version && cargo --version
    - cd rust
    - cargo build --release
    - cargo doc
  artifacts:
    paths:
    - rust/target/release/fatcat*
    - rust/target/doc/fatcat*
    - rust/target/doc/*.css
    - rust/target/doc/*.js
    - rust/target/doc/*.woff
    - rust/target/doc/*.svg
    expire_in: 1 year

